# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']
        #  - targets: ['https://gitlab.talksuresa.co.za:8083/metrics']
        #    labels:
        #     instance: 'traefik'


  # - job_name: 'traefik'

    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s

    # dns_sd_configs:
    # - names:
    #   - 'tasks.traefik'
    #   type: 'A'
    #   port: 8080

  - job_name: 'traefik'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: https
    static_configs:
    - targets:
      - gitlab.talksuresa.co.za.:8083

  - job_name: 'cadvisor'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /
    scheme: https
    static_configs:
    - targets:
      - ts-lnx-dock02:8081

  # - job_name: 'cadvisor'
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.cadvisor'
  #     type: 'A'
  #     port: 8080
    
    # # The targets specified by the static config.
    # targets:
    #   [ - '<host>' ]

    # # Labels assigned to all metrics scraped from the targets.
    # labels:
    # [ <labelname>: <labelvalue> ... ]
